### ISSUE TITLE
Discussion on wildfly-swarm, fatjar packaging

### ISSUE THREAD

**Issue by agoncal** [wildfly-swarm/wildfly-swarm#30]
Hi all,

I'm interested in knowing more about the internal structure of the Fatjar. When I look at the examples, I see the following structure

```
wildfly-swarm-archive
   __redirected
   app
   m2repo
   modules
   org
   schema
```
Under the `app` directory I find the application, packaged in a war. What puzzles me is the split between `m2repo` and `modules`. I was expecting to find the same structure as Wildly under `modules` : a mix of module descriptors and jar files. But instead, I could only find the module descriptors (`main/module.xml`) without jars (all under `m2repo`). 

Any reason why this split is done ? Any documentation on the fatjar structure and the classloading documentation ? 

Thanks

**Comment by bobmcwhirter** [comment]
It's changing for alpha2 but I'll will certainly be sure to document he format. 

--

**Comment by bobmcwhirter** [comment]
I'll reply more fully tomorrow when I'm not on my phone also. I don't mean to be terse. 

--

**Comment by bobmcwhirter** [comment]
Okay!

While some of this is changing for Alpha2, here's the basic run-down...

We consume the module.xml files from the -feature-pack.zip files that WildFly-Core and WildFly proper produce.

The feature-pack uses <artifact> to reference jars, typically using an expression like ${groupId:artifactId}.

It includes a wildfly-feature-pack.xml at the root which can be used to determine the *version* of the groupId:artifactId expression.

JBoss Modules then has the capability to load <artifact> from a Maven repository, including the capability to download the artifact if it's not present.

In Alpha2, we support a bundleDependencies=false in the plugin configuration, which will cause the m2repo/ to *not* be created, as it assumes you have an M2_REPO on your filesystem.  The default still stuffs all the dependencies under m2repo/... in the uberjar.

With a small modification to jboss-modules, we add the ability to not just resolve artifacts from M2_REPO externally, but to first try $UBERJAR/m2repo/... to find them.

Hence the split between modules/* and m2repo/*, with one referencing jars in the other.

Another, less important reason, is if WildFly-Swarm uses someJar-1.0.jar, and your application also uses it, we attempt to not include 2 copies (one under modules/ and one under m2repo/) because that'd be needless duplication.

A single copy is kept under m2repo/... referenced by both your app and by WildFly-Swarm internals.

The __redirected/, org/ and schema/ stuff you see in the uberjar is just a verbatim copy of the jboss-modules.jar with a few classes replaced from WildFly-Swarm in order to work how we need it to.  Since WildFly is completely based upon the modular classloading system of JBoss Modules, we have to promote jboss-modules to the root in order to effectively bootstrap into it.

In Alpha2, since we support running from an IDE using the IDE's classpath, classloadering gets more complicated internally, with tricks occurring that should be completely transparent to the end-user.

Alpha2 is still in progress, and I already have some more changes to apply against the current HEAD as we re-think the multiple-ways-to-run scenarios.

Currently we support:

* java -jar myapp-swarm.jar
* mvn wildfly-swarm:run
* IDE > Run... MyMain
* IDE > Run... org.wildfly.swarm.Swarm (if you provide no mainClass; .war deployments)

**Comment by agoncal** [comment]
Thanks for the clarification. I can see that things are still moving ;o)

**Comment by kenfinnigan** [comment]
Will be documenting this as part of #44
