### ISSUE TITLE
Support static content for regular war/jaxrs deployments

### ISSUE THREAD

**Issue by fbricon** [wildfly-swarm/wildfly-swarm#49]
This is request is quite similar to https://github.com/wildfly-swarm/wildfly-swarm/issues/21 actually.

The goal here is to deploy both classes AND static resources in the same deployment.

Icing on the cake : static resources would be reloaded automatically if changed.

**Comment by bobmcwhirter** [comment]
So, here is my ignorance... Is there a standard way in JavaEE this is already supported?  Or does everyone manually install some StaticResourceServlet or Filter?

**Comment by fbricon** [comment]
No idea about the gritty details, but undertow is capable of serving static files once they've changed on disk (there was a bug in early versions where files where cached indefinitely).

All app servers I've seen are capable to do it OOTB, AFAIK, and none require a specific filter. For JSPs, it might be needed to run the server in a Dev mode so the pages can be recompiled on change.

You should prolly ping the wildfly/undertow devs for more details.

**Comment by bobmcwhirter** [comment]
Okay!

https://github.com/wildfly-swarm/wildfly-swarm/blob/master/integration-tests/static-war/src/test/java/org/wildfly/swarm/integration/staticcontent/war/StaticContentWarTest.java

You can edit your static content and they will appear.  It uses a mixture of file and classloader-based undertow resource handlers, so that filesystem wins, allowing continual editing within a running app.

So you can

warDeployment.staticContent() which will lay it on top of the normal context path, based upon filesystem paths (or classpath).

warDeployment.staticContent( "/different" ) will search the same, but serve under sub-path of /different.

warDeployment.staticContent("/different", "foo/bar" ) will search in foo/bar/* directory or classpath for the path, and serve it under $APP_CONTENT/different.

I think this solves all the use-cases.

Re-open (or open another) if not.

**Comment by bobmcwhirter** [comment]
Not sufficient solution for layering on top of JAXRS or servlets, alas.

**Comment by fbricon** [comment]
Sounds promising, we're getting there :-)

**Comment by bobmcwhirter** [comment]
I'll leave this open as a reminder to figure out how to test modifications in an automated fashion, but it now layers well on top of JAX-RS.

https://github.com/wildfly-swarm/wildfly-swarm/blob/master/integration-tests/jaxrs/src/test/java/org/wildfly/swarm/integration/jaxrs/JAXRSTest.java

@Resource bound to / while static-content gets first shot at serving.

Directory-listings are not possible, but I think that's okay.

**Comment by bobmcwhirter** [comment]
Once again, fixed, again, once more.

See https://github.com/wildfly-swarm/wildfly-swarm/issues/62
